using air_reservation.Models.Flight_Model_;
using Microsoft.EntityFrameworkCore;

namespace air_reservation.Data_Access_Layer
{
    public class FlightSeeding
    {
        public static void Seed(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Flight>().HasData(
                new Flight
                {
                    Id = 1,
                    FlightNumber = "AI101",
                    Airline = "Air India",
                    Aircraft = "A320",
                    Origin = "Delhi",
                    Destination = "Mumbai",
                    DepartureDateTime = new DateTime(2025, 6, 15, 7, 30, 0),
                    ArrivalDateTime = new DateTime(2025, 6, 15, 9, 30, 0),
                    BusinessPrice = 9500.00m,
                    EconomyPrice = 4800.00m,
                    TotalBusinessSeats = 20,
                    AvailableBusinessSeats = 20,
                    TotalEconomySeats = 120,
                    AvailableEconomySeats = 120,
                    Status = 0
                },
            new Flight
            {
                Id = 2,
                FlightNumber = "6E305",
                Airline = "IndiGo",
                Aircraft = "A321",
                Origin = "Mumbai",
                Destination = "Bangalore",
                DepartureDateTime = new DateTime(2025, 6, 15, 12, 0, 0),
                ArrivalDateTime = new DateTime(2025, 6, 15, 14, 0, 0),
                BusinessPrice = 8900.00m,
                EconomyPrice = 4200.00m,
                TotalBusinessSeats = 24,
                AvailableBusinessSeats = 24,
                TotalEconomySeats = 140,
                AvailableEconomySeats = 140,
                Status = 0
            },
            new Flight
            {
                Id = 3,
                FlightNumber = "SG101",
                Airline = "SpiceJet",
                Aircraft = "Boeing 737",
                Origin = "Chennai",
                Destination = "Hyderabad",
                DepartureDateTime = new DateTime(2025, 6, 16, 6, 0, 0),
                ArrivalDateTime = new DateTime(2025, 6, 16, 7, 30, 0),
                BusinessPrice = 7500.00m,
                EconomyPrice = 3500.00m,
                TotalBusinessSeats = 16,
                AvailableBusinessSeats = 16,
                TotalEconomySeats = 100,
                AvailableEconomySeats = 100,
                Status = 0
            },
            new Flight
            {
                Id = 4,
                FlightNumber = "AI303",
                Airline = "Air India",
                Aircraft = "A320neo",
                Origin = "Kolkata",
                Destination = "Delhi",
                DepartureDateTime = new DateTime(2025, 6, 17, 9, 0, 0),
                ArrivalDateTime = new DateTime(2025, 6, 17, 11, 30, 0),
                BusinessPrice = 9700.00m,
                EconomyPrice = 4600.00m,
                TotalBusinessSeats = 22,
                AvailableBusinessSeats = 22,
                TotalEconomySeats = 130,
                AvailableEconomySeats = 130,
                Status = 0
            },
            new Flight
            {
                Id = 5,
                FlightNumber = "6E122",
                Airline = "IndiGo",
                Aircraft = "A320",
                Origin = "Pune",
                Destination = "Ahmedabad",
                DepartureDateTime = new DateTime(2025, 6, 18, 8, 0, 0),
                ArrivalDateTime = new DateTime(2025, 6, 18, 9, 15, 0),
                BusinessPrice = 7300.00m,
                EconomyPrice = 3300.00m,
                TotalBusinessSeats = 18,
                AvailableBusinessSeats = 18,
                TotalEconomySeats = 110,
                AvailableEconomySeats = 110,
                Status = 0
            },
            new Flight
            {
                Id = 6,
                FlightNumber = "G8176",
                Airline = "GoAir",
                Aircraft = "A320",
                Origin = "Delhi",
                Destination = "Lucknow",
                DepartureDateTime = new DateTime(2025, 6, 19, 7, 45, 0),
                ArrivalDateTime = new DateTime(2025, 6, 19, 9, 0, 0),
                BusinessPrice = 6800.00m,
                EconomyPrice = 2900.00m,
                TotalBusinessSeats = 15,
                AvailableBusinessSeats = 15,
                TotalEconomySeats = 95,
                AvailableEconomySeats = 95,
                Status = 0
            },
            new Flight
            {
                Id = 7,
                FlightNumber = "SG211",
                Airline = "SpiceJet",
                Aircraft = "Q400",
                Origin = "Bangalore",
                Destination = "Hyderabad",
                DepartureDateTime = new DateTime(2025, 6, 20, 10, 0, 0),
                ArrivalDateTime = new DateTime(2025, 6, 20, 11, 15, 0),
                BusinessPrice = 7200.00m,
                EconomyPrice = 3100.00m,
                TotalBusinessSeats = 12,
                AvailableBusinessSeats = 12,
                TotalEconomySeats = 90,
                AvailableEconomySeats = 90,
                Status = 0
            },
            new Flight
            {
                Id = 8,
                FlightNumber = "6E654",
                Airline = "IndiGo",
                Aircraft = "A320",
                Origin = "Jaipur",
                Destination = "Delhi",
                DepartureDateTime = new DateTime(2025, 6, 21, 15, 0, 0),
                ArrivalDateTime = new DateTime(2025, 6, 21, 16, 0, 0),
                BusinessPrice = 6900.00m,
                EconomyPrice = 2800.00m,
                TotalBusinessSeats = 20,
                AvailableBusinessSeats = 20,
                TotalEconomySeats = 110,
                AvailableEconomySeats = 110,
                Status = 0
            },
            new Flight
            {
                Id = 9,
                FlightNumber = "AI879",
                Airline = "Air India",
                Aircraft = "A321",
                Origin = "Mumbai",
                Destination = "Goa",
                DepartureDateTime = new DateTime(2025, 6, 22, 13, 30, 0),
                ArrivalDateTime = new DateTime(2025, 6, 22, 14, 45, 0),
                BusinessPrice = 8600.00m,
                EconomyPrice = 3900.00m,
                TotalBusinessSeats = 25,
                AvailableBusinessSeats = 25,
                TotalEconomySeats = 140,
                AvailableEconomySeats = 140,
                Status = 0
            },
            new Flight
            {
                Id = 10,
                FlightNumber = "G8320",
                Airline = "GoAir",
                Aircraft = "A320neo",
                Origin = "Hyderabad",
                Destination = "Chennai",
                DepartureDateTime = new DateTime(2025, 6, 23, 6, 45, 0),
                ArrivalDateTime = new DateTime(2025, 6, 23, 8, 0, 0),
                BusinessPrice = 7700.00m,
                EconomyPrice = 3600.00m,
                TotalBusinessSeats = 18,
                AvailableBusinessSeats = 18,
                TotalEconomySeats = 115,
                AvailableEconomySeats = 115,
                Status = 0
            },

            //same source to destination multiple flights for domestic flights 

            new Flight
            {
                Id = 11,
                FlightNumber = "UK201",
                Airline = "Vistara",
                Aircraft = "A321neo",
                Origin = "Delhi",
                Destination = "Mumbai",
                DepartureDateTime = new DateTime(2025, 6, 15, 18, 30, 0),
                ArrivalDateTime = new DateTime(2025, 6, 15, 20, 30, 0),
                BusinessPrice = 9700.00m,
                EconomyPrice = 4900.00m,
                TotalBusinessSeats = 18,
                AvailableBusinessSeats = 18,
                TotalEconomySeats = 120,
                AvailableEconomySeats = 120,
                Status = 0
            },
new Flight
{
    Id = 12,
    FlightNumber = "I5123",
    Airline = "AirAsia India",
    Aircraft = "A320neo",
    Origin = "Mumbai",
    Destination = "Bangalore",
    DepartureDateTime = new DateTime(2025, 6, 15, 16, 0, 0),
    ArrivalDateTime = new DateTime(2025, 6, 15, 18, 0, 0),
    BusinessPrice = 8800.00m,
    EconomyPrice = 4300.00m,
    TotalBusinessSeats = 20,
    AvailableBusinessSeats = 20,
    TotalEconomySeats = 135,
    AvailableEconomySeats = 135,
    Status = 0
},
new Flight
{
    Id = 13,
    FlightNumber = "AK702",
    Airline = "AirAsia",
    Aircraft = "A321XLR",
    Origin = "Chennai",
    Destination = "Hyderabad",
    DepartureDateTime = new DateTime(2025, 6, 17, 8, 15, 0),
    ArrivalDateTime = new DateTime(2025, 6, 17, 9, 45, 0),
    BusinessPrice = 7700.00m,
    EconomyPrice = 3600.00m,
    TotalBusinessSeats = 18,
    AvailableBusinessSeats = 18,
    TotalEconomySeats = 110,
    AvailableEconomySeats = 110,
    Status = 0
},
new Flight
{
    Id = 14,
    FlightNumber = "AI401",
    Airline = "Air India Express",
    Aircraft = "Boeing 737 MAX",
    Origin = "Kolkata",
    Destination = "Delhi",
    DepartureDateTime = new DateTime(2025, 6, 17, 15, 0, 0),
    ArrivalDateTime = new DateTime(2025, 6, 17, 17, 30, 0),
    BusinessPrice = 9600.00m,
    EconomyPrice = 4700.00m,
    TotalBusinessSeats = 24,
    AvailableBusinessSeats = 24,
    TotalEconomySeats = 130,
    AvailableEconomySeats = 130,
    Status = 0
},
new Flight
{
    Id = 15,
    FlightNumber = "QP122",
    Airline = "Akasa Air",
    Aircraft = "B737-8",
    Origin = "Pune",
    Destination = "Ahmedabad",
    DepartureDateTime = new DateTime(2025, 6, 18, 17, 0, 0),
    ArrivalDateTime = new DateTime(2025, 6, 18, 18, 15, 0),
    BusinessPrice = 7200.00m,
    EconomyPrice = 3100.00m,
    TotalBusinessSeats = 14,
    AvailableBusinessSeats = 14,
    TotalEconomySeats = 100,
    AvailableEconomySeats = 100,
    Status = 0
},
new Flight
{
    Id = 16,
    FlightNumber = "UK567",
    Airline = "Vistara",
    Aircraft = "A320neo",
    Origin = "Delhi",
    Destination = "Lucknow",
    DepartureDateTime = new DateTime(2025, 6, 19, 18, 0, 0),
    ArrivalDateTime = new DateTime(2025, 6, 19, 19, 15, 0),
    BusinessPrice = 6900.00m,
    EconomyPrice = 3000.00m,
    TotalBusinessSeats = 12,
    AvailableBusinessSeats = 12,
    TotalEconomySeats = 90,
    AvailableEconomySeats = 90,
    Status = 0
},
new Flight
{
    Id = 17,
    FlightNumber = "IX201",
    Airline = "Air India Express",
    Aircraft = "Boeing 737",
    Origin = "Bangalore",
    Destination = "Hyderabad",
    DepartureDateTime = new DateTime(2025, 6, 20, 16, 0, 0),
    ArrivalDateTime = new DateTime(2025, 6, 20, 17, 15, 0),
    BusinessPrice = 7000.00m,
    EconomyPrice = 3200.00m,
    TotalBusinessSeats = 10,
    AvailableBusinessSeats = 10,
    TotalEconomySeats = 95,
    AvailableEconomySeats = 95,
    Status = 0
},
new Flight
{
    Id = 18,
    FlightNumber = "QP345",
    Airline = "Akasa Air",
    Aircraft = "B737-800",
    Origin = "Jaipur",
    Destination = "Delhi",
    DepartureDateTime = new DateTime(2025, 6, 21, 17, 0, 0),
    ArrivalDateTime = new DateTime(2025, 6, 21, 18, 0, 0),
    BusinessPrice = 7000.00m,
    EconomyPrice = 2700.00m,
    TotalBusinessSeats = 16,
    AvailableBusinessSeats = 16,
    TotalEconomySeats = 105,
    AvailableEconomySeats = 105,
    Status = 0
},
new Flight
{
    Id = 19,
    FlightNumber = "IX333",
    Airline = "Air India Express",
    Aircraft = "B737 MAX",
    Origin = "Mumbai",
    Destination = "Goa",
    DepartureDateTime = new DateTime(2025, 6, 23, 10, 0, 0),
    ArrivalDateTime = new DateTime(2025, 6, 23, 11, 15, 0),
    BusinessPrice = 8500.00m,
    EconomyPrice = 3700.00m,
    TotalBusinessSeats = 20,
    AvailableBusinessSeats = 20,
    TotalEconomySeats = 130,
    AvailableEconomySeats = 130,
    Status = 0
},
new Flight
{
    Id = 20,
    FlightNumber = "UK788",
    Airline = "Vistara",
    Aircraft = "A320",
    Origin = "Hyderabad",
    Destination = "Chennai",
    DepartureDateTime = new DateTime(2025, 6, 23, 13, 30, 0),
    ArrivalDateTime = new DateTime(2025, 6, 23, 14, 45, 0),
    BusinessPrice = 7600.00m,
    EconomyPrice = 3500.00m,
    TotalBusinessSeats = 16,
    AvailableBusinessSeats = 16,
    TotalEconomySeats = 115,
    AvailableEconomySeats = 115,
    Status = 0
},

   // round trip for domestic flights (for first 10 flights)

   new Flight
   {
       Id = 21,
       FlightNumber = "AI102",
       Airline = "Air India",
       Aircraft = "A320",
       Origin = "Mumbai",
       Destination = "Delhi",
       DepartureDateTime = new DateTime(2025, 6, 18, 18, 0, 0),
       ArrivalDateTime = new DateTime(2025, 6, 18, 20, 0, 0),
       BusinessPrice = 9400.00m,
       EconomyPrice = 4700.00m,
       TotalBusinessSeats = 20,
       AvailableBusinessSeats = 20,
       TotalEconomySeats = 120,
       AvailableEconomySeats = 120,
       Status = 0
   },
    new Flight
    {
        Id = 22,
        FlightNumber = "6E306",
        Airline = "IndiGo",
        Aircraft = "A321",
        Origin = "Bangalore",
        Destination = "Mumbai",
        DepartureDateTime = new DateTime(2025, 6, 17, 15, 0, 0),
        ArrivalDateTime = new DateTime(2025, 6, 17, 17, 0, 0),
        BusinessPrice = 8800.00m,
        EconomyPrice = 4100.00m,
        TotalBusinessSeats = 24,
        AvailableBusinessSeats = 24,
        TotalEconomySeats = 140,
        AvailableEconomySeats = 140,
        Status = 0
    },
    new Flight
    {
        Id = 23,
        FlightNumber = "SG102",
        Airline = "SpiceJet",
        Aircraft = "Boeing 737",
        Origin = "Hyderabad",
        Destination = "Chennai",
        DepartureDateTime = new DateTime(2025, 6, 19, 8, 30, 0),
        ArrivalDateTime = new DateTime(2025, 6, 19, 10, 0, 0),
        BusinessPrice = 7400.00m,
        EconomyPrice = 3400.00m,
        TotalBusinessSeats = 16,
        AvailableBusinessSeats = 16,
        TotalEconomySeats = 100,
        AvailableEconomySeats = 100,
        Status = 0
    },
    new Flight
    {
        Id = 24,
        FlightNumber = "AI304",
        Airline = "Air India",
        Aircraft = "A320neo",
        Origin = "Delhi",
        Destination = "Kolkata",
        DepartureDateTime = new DateTime(2025, 6, 19, 14, 30, 0),
        ArrivalDateTime = new DateTime(2025, 6, 19, 17, 0, 0),
        BusinessPrice = 9600.00m,
        EconomyPrice = 4500.00m,
        TotalBusinessSeats = 22,
        AvailableBusinessSeats = 22,
        TotalEconomySeats = 130,
        AvailableEconomySeats = 130,
        Status = 0
    },
    new Flight
    {
        Id = 25,
        FlightNumber = "6E123",
        Airline = "IndiGo",
        Aircraft = "A320",
        Origin = "Ahmedabad",
        Destination = "Pune",
        DepartureDateTime = new DateTime(2025, 6, 20, 10, 0, 0),
        ArrivalDateTime = new DateTime(2025, 6, 20, 11, 15, 0),
        BusinessPrice = 7200.00m,
        EconomyPrice = 3200.00m,
        TotalBusinessSeats = 18,
        AvailableBusinessSeats = 18,
        TotalEconomySeats = 110,
        AvailableEconomySeats = 110,
        Status = 0
    },
    new Flight
    {
        Id = 26,
        FlightNumber = "G8177",
        Airline = "GoAir",
        Aircraft = "A320",
        Origin = "Lucknow",
        Destination = "Delhi",
        DepartureDateTime = new DateTime(2025, 6, 21, 11, 0, 0),
        ArrivalDateTime = new DateTime(2025, 6, 21, 12, 15, 0),
        BusinessPrice = 6700.00m,
        EconomyPrice = 2800.00m,
        TotalBusinessSeats = 15,
        AvailableBusinessSeats = 15,
        TotalEconomySeats = 95,
        AvailableEconomySeats = 95,
        Status = 0
    },
    new Flight
    {
        Id = 27,
        FlightNumber = "SG212",
        Airline = "SpiceJet",
        Aircraft = "Q400",
        Origin = "Hyderabad",
        Destination = "Bangalore",
        DepartureDateTime = new DateTime(2025, 6, 22, 12, 15, 0),
        ArrivalDateTime = new DateTime(2025, 6, 22, 13, 30, 0),
        BusinessPrice = 7100.00m,
        EconomyPrice = 3000.00m,
        TotalBusinessSeats = 12,
        AvailableBusinessSeats = 12,
        TotalEconomySeats = 90,
        AvailableEconomySeats = 90,
        Status = 0
    },
    new Flight
    {
        Id = 28,
        FlightNumber = "6E655",
        Airline = "IndiGo",
        Aircraft = "A320",
        Origin = "Delhi",
        Destination = "Jaipur",
        DepartureDateTime = new DateTime(2025, 6, 22, 17, 0, 0),
        ArrivalDateTime = new DateTime(2025, 6, 22, 18, 0, 0),
        BusinessPrice = 6800.00m,
        EconomyPrice = 2700.00m,
        TotalBusinessSeats = 20,
        AvailableBusinessSeats = 20,
        TotalEconomySeats = 110,
        AvailableEconomySeats = 110,
        Status = 0
    },
    new Flight
    {
        Id = 29,
        FlightNumber = "AI880",
        Airline = "Air India",
        Aircraft = "A321",
        Origin = "Goa",
        Destination = "Mumbai",
        DepartureDateTime = new DateTime(2025, 6, 24, 10, 30, 0),
        ArrivalDateTime = new DateTime(2025, 6, 24, 11, 45, 0),
        BusinessPrice = 8500.00m,
        EconomyPrice = 3800.00m,
        TotalBusinessSeats = 25,
        AvailableBusinessSeats = 25,
        TotalEconomySeats = 140,
        AvailableEconomySeats = 140,
        Status = 0
    },
    new Flight
    {
        Id = 30,
        FlightNumber = "G8321",
        Airline = "GoAir",
        Aircraft = "A320neo",
        Origin = "Chennai",
        Destination = "Hyderabad",
        DepartureDateTime = new DateTime(2025, 6, 25, 9, 0, 0),
        ArrivalDateTime = new DateTime(2025, 6, 25, 10, 15, 0),
        BusinessPrice = 7600.00m,
        EconomyPrice = 3500.00m,
        TotalBusinessSeats = 18,
        AvailableBusinessSeats = 18,
        TotalEconomySeats = 115,
        AvailableEconomySeats = 115,
        Status = 0
    },

    // internal flight data ( origin Indian cities and location abroad)

    new Flight
    {
        Id = 41,
        FlightNumber = "AI101",
        Airline = "Air India",
        Aircraft = "Boeing 777",
        Origin = "Delhi",
        Destination = "New York",
        DepartureDateTime = new DateTime(2025, 7, 1, 2, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 1, 13, 45, 0),
        BusinessPrice = 155000.00m,
        EconomyPrice = 65000.00m,
        TotalBusinessSeats = 40,
        AvailableBusinessSeats = 40,
        TotalEconomySeats = 200,
        AvailableEconomySeats = 200,
        Status = 0
    },
    new Flight
    {
        Id = 42,
        FlightNumber = "BA142",
        Airline = "British Airways",
        Aircraft = "Boeing 787",
        Origin = "Mumbai",
        Destination = "London",
        DepartureDateTime = new DateTime(2025, 7, 2, 1, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 2, 7, 45, 0),
        BusinessPrice = 140000.00m,
        EconomyPrice = 58000.00m,
        TotalBusinessSeats = 35,
        AvailableBusinessSeats = 35,
        TotalEconomySeats = 180,
        AvailableEconomySeats = 180,
        Status = 0
    },
    new Flight
    {
        Id = 43,
        FlightNumber = "EK501",
        Airline = "Emirates",
        Aircraft = "Airbus A380",
        Origin = "Delhi",
        Destination = "Dubai",
        DepartureDateTime = new DateTime(2025, 7, 3, 4, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 3, 6, 30, 0),
        BusinessPrice = 70000.00m,
        EconomyPrice = 25000.00m,
        TotalBusinessSeats = 50,
        AvailableBusinessSeats = 50,
        TotalEconomySeats = 300,
        AvailableEconomySeats = 300,
        Status = 0
    },
    new Flight
    {
        Id = 44,
        FlightNumber = "SQ403",
        Airline = "Singapore Airlines",
        Aircraft = "Airbus A350",
        Origin = "Mumbai",
        Destination = "Singapore",
        DepartureDateTime = new DateTime(2025, 7, 4, 23, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 5, 7, 0, 0),
        BusinessPrice = 90000.00m,
        EconomyPrice = 35000.00m,
        TotalBusinessSeats = 30,
        AvailableBusinessSeats = 30,
        TotalEconomySeats = 220,
        AvailableEconomySeats = 220,
        Status = 0
    },
    new Flight
    {
        Id = 45,
        FlightNumber = "LH757",
        Airline = "Lufthansa",
        Aircraft = "Boeing 747",
        Origin = "Bangalore",
        Destination = "Frankfurt",
        DepartureDateTime = new DateTime(2025, 7, 5, 3, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 5, 12, 0, 0),
        BusinessPrice = 145000.00m,
        EconomyPrice = 60000.00m,
        TotalBusinessSeats = 38,
        AvailableBusinessSeats = 38,
        TotalEconomySeats = 210,
        AvailableEconomySeats = 210,
        Status = 0
    },
    new Flight
    {
        Id = 46,
        FlightNumber = "QR571",
        Airline = "Qatar Airways",
        Aircraft = "Boeing 777",
        Origin = "Delhi",
        Destination = "Doha",
        DepartureDateTime = new DateTime(2025, 7, 6, 2, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 6, 5, 0, 0),
        BusinessPrice = 80000.00m,
        EconomyPrice = 30000.00m,
        TotalBusinessSeats = 42,
        AvailableBusinessSeats = 42,
        TotalEconomySeats = 250,
        AvailableEconomySeats = 250,
        Status = 0
    },
    new Flight
    {
        Id = 47,
        FlightNumber = "CX695",
        Airline = "Cathay Pacific",
        Aircraft = "Airbus A350",
        Origin = "Delhi",
        Destination = "Hong Kong",
        DepartureDateTime = new DateTime(2025, 7, 7, 0, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 7, 8, 30, 0),
        BusinessPrice = 115000.00m,
        EconomyPrice = 42000.00m,
        TotalBusinessSeats = 36,
        AvailableBusinessSeats = 36,
        TotalEconomySeats = 230,
        AvailableEconomySeats = 230,
        Status = 0
    },
    new Flight
    {
        Id = 48,
        FlightNumber = "JL750",
        Airline = "Japan Airlines",
        Aircraft = "Boeing 787",
        Origin = "Delhi",
        Destination = "Tokyo",
        DepartureDateTime = new DateTime(2025, 7, 8, 22, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 9, 9, 0, 0),
        BusinessPrice = 160000.00m,
        EconomyPrice = 67000.00m,
        TotalBusinessSeats = 34,
        AvailableBusinessSeats = 34,
        TotalEconomySeats = 215,
        AvailableEconomySeats = 215,
        Status = 0
    },
    new Flight
    {
        Id = 49,
        FlightNumber = "AF225",
        Airline = "Air France",
        Aircraft = "Boeing 777",
        Origin = "Delhi",
        Destination = "Paris",
        DepartureDateTime = new DateTime(2025, 7, 9, 1, 15, 0),
        ArrivalDateTime = new DateTime(2025, 7, 9, 11, 0, 0),
        BusinessPrice = 150000.00m,
        EconomyPrice = 62000.00m,
        TotalBusinessSeats = 40,
        AvailableBusinessSeats = 40,
        TotalEconomySeats = 220,
        AvailableEconomySeats = 220,
        Status = 0
    },
    new Flight
    {
        Id = 50,
        FlightNumber = "UA83",
        Airline = "United Airlines",
        Aircraft = "Boeing 787",
        Origin = "Delhi",
        Destination = "Chicago",
        DepartureDateTime = new DateTime(2025, 7, 10, 4, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 10, 14, 15, 0),
        BusinessPrice = 170000.00m,
        EconomyPrice = 70000.00m,
        TotalBusinessSeats = 44,
        AvailableBusinessSeats = 44,
        TotalEconomySeats = 240,
        AvailableEconomySeats = 240,
        Status = 0
    },

     // round trip

     new Flight
     {
         Id = 51,
         FlightNumber = "AI102",
         Airline = "Air India",
         Aircraft = "Boeing 777",
         Origin = "New York",
         Destination = "Delhi",
         DepartureDateTime = new DateTime(2025, 7, 6, 16, 0, 0),
         ArrivalDateTime = new DateTime(2025, 7, 7, 5, 15, 0),
         BusinessPrice = 155000.00m,
         EconomyPrice = 65000.00m,
         TotalBusinessSeats = 40,
         AvailableBusinessSeats = 40,
         TotalEconomySeats = 200,
         AvailableEconomySeats = 200,
         Status = 0
     },
    new Flight
    {
        Id = 52,
        FlightNumber = "BA143",
        Airline = "British Airways",
        Aircraft = "Boeing 787",
        Origin = "London",
        Destination = "Mumbai",
        DepartureDateTime = new DateTime(2025, 7, 5, 13, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 5, 23, 15, 0),
        BusinessPrice = 140000.00m,
        EconomyPrice = 58000.00m,
        TotalBusinessSeats = 35,
        AvailableBusinessSeats = 35,
        TotalEconomySeats = 180,
        AvailableEconomySeats = 180,
        Status = 0
    },
    new Flight
    {
        Id = 53,
        FlightNumber = "EK502",
        Airline = "Emirates",
        Aircraft = "Airbus A380",
        Origin = "Dubai",
        Destination = "Delhi",
        DepartureDateTime = new DateTime(2025, 7, 6, 10, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 6, 14, 0, 0),
        BusinessPrice = 70000.00m,
        EconomyPrice = 25000.00m,
        TotalBusinessSeats = 50,
        AvailableBusinessSeats = 50,
        TotalEconomySeats = 300,
        AvailableEconomySeats = 300,
        Status = 0
    },
    new Flight
    {
        Id = 54,
        FlightNumber = "SQ404",
        Airline = "Singapore Airlines",
        Aircraft = "Airbus A350",
        Origin = "Singapore",
        Destination = "Mumbai",
        DepartureDateTime = new DateTime(2025, 7, 8, 11, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 8, 19, 0, 0),
        BusinessPrice = 90000.00m,
        EconomyPrice = 35000.00m,
        TotalBusinessSeats = 30,
        AvailableBusinessSeats = 30,
        TotalEconomySeats = 220,
        AvailableEconomySeats = 220,
        Status = 0
    },
    new Flight
    {
        Id = 55,
        FlightNumber = "LH758",
        Airline = "Lufthansa",
        Aircraft = "Boeing 747",
        Origin = "Frankfurt",
        Destination = "Bangalore",
        DepartureDateTime = new DateTime(2025, 7, 9, 14, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 10, 2, 0, 0),
        BusinessPrice = 145000.00m,
        EconomyPrice = 60000.00m,
        TotalBusinessSeats = 38,
        AvailableBusinessSeats = 38,
        TotalEconomySeats = 210,
        AvailableEconomySeats = 210,
        Status = 0
    },
    new Flight
    {
        Id = 56,
        FlightNumber = "QR572",
        Airline = "Qatar Airways",
        Aircraft = "Boeing 777",
        Origin = "Doha",
        Destination = "Delhi",
        DepartureDateTime = new DateTime(2025, 7, 7, 6, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 7, 10, 0, 0),
        BusinessPrice = 80000.00m,
        EconomyPrice = 30000.00m,
        TotalBusinessSeats = 42,
        AvailableBusinessSeats = 42,
        TotalEconomySeats = 250,
        AvailableEconomySeats = 250,
        Status = 0
    },
    new Flight
    {
        Id = 57,
        FlightNumber = "CX696",
        Airline = "Cathay Pacific",
        Aircraft = "Airbus A350",
        Origin = "Hong Kong",
        Destination = "Delhi",
        DepartureDateTime = new DateTime(2025, 7, 10, 12, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 10, 18, 30, 0),
        BusinessPrice = 115000.00m,
        EconomyPrice = 42000.00m,
        TotalBusinessSeats = 36,
        AvailableBusinessSeats = 36,
        TotalEconomySeats = 230,
        AvailableEconomySeats = 230,
        Status = 0
    },
    new Flight
    {
        Id = 58,
        FlightNumber = "JL751",
        Airline = "Japan Airlines",
        Aircraft = "Boeing 787",
        Origin = "Tokyo",
        Destination = "Delhi",
        DepartureDateTime = new DateTime(2025, 7, 11, 20, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 12, 6, 30, 0),
        BusinessPrice = 160000.00m,
        EconomyPrice = 67000.00m,
        TotalBusinessSeats = 34,
        AvailableBusinessSeats = 34,
        TotalEconomySeats = 215,
        AvailableEconomySeats = 215,
        Status = 0
    },
    new Flight
    {
        Id = 59,
        FlightNumber = "AF226",
        Airline = "Air France",
        Aircraft = "Boeing 777",
        Origin = "Paris",
        Destination = "Delhi",
        DepartureDateTime = new DateTime(2025, 7, 12, 3, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 12, 14, 0, 0),
        BusinessPrice = 150000.00m,
        EconomyPrice = 62000.00m,
        TotalBusinessSeats = 40,
        AvailableBusinessSeats = 40,
        TotalEconomySeats = 220,
        AvailableEconomySeats = 220,
        Status = 0
    },
    new Flight
    {
        Id = 60,
        FlightNumber = "UA84",
        Airline = "United Airlines",
        Aircraft = "Boeing 787",
        Origin = "Chicago",
        Destination = "Delhi",
        DepartureDateTime = new DateTime(2025, 7, 13, 15, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 14, 5, 0, 0),
        BusinessPrice = 170000.00m,
        EconomyPrice = 70000.00m,
        TotalBusinessSeats = 44,
        AvailableBusinessSeats = 44,
        TotalEconomySeats = 240,
        AvailableEconomySeats = 240,
        Status = 0
    },

    // international flight (origin and destination outside india)

    new Flight
    {
        Id = 61,
        FlightNumber = "DL145",
        Airline = "Delta Airlines",
        Aircraft = "Boeing 737",
        Origin = "New York",
        Destination = "Los Angeles",
        DepartureDateTime = new DateTime(2025, 7, 10, 9, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 10, 12, 15, 0),
        BusinessPrice = 60000.00m,
        EconomyPrice = 22000.00m,
        TotalBusinessSeats = 20,
        AvailableBusinessSeats = 20,
        TotalEconomySeats = 150,
        AvailableEconomySeats = 150,
        Status = 0
    },
    new Flight
    {
        Id = 62,
        FlightNumber = "BA256",
        Airline = "British Airways",
        Aircraft = "Airbus A320",
        Origin = "London",
        Destination = "Edinburgh",
        DepartureDateTime = new DateTime(2025, 7, 11, 8, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 11, 10, 0, 0),
        BusinessPrice = 40000.00m,
        EconomyPrice = 15000.00m,
        TotalBusinessSeats = 15,
        AvailableBusinessSeats = 15,
        TotalEconomySeats = 120,
        AvailableEconomySeats = 120,
        Status = 0
    },
    new Flight
    {
        Id = 63,
        FlightNumber = "AF341",
        Airline = "Air France",
        Aircraft = "Airbus A321",
        Origin = "Paris",
        Destination = "Nice",
        DepartureDateTime = new DateTime(2025, 7, 12, 13, 45, 0),
        ArrivalDateTime = new DateTime(2025, 7, 12, 15, 10, 0),
        BusinessPrice = 38000.00m,
        EconomyPrice = 12000.00m,
        TotalBusinessSeats = 12,
        AvailableBusinessSeats = 12,
        TotalEconomySeats = 110,
        AvailableEconomySeats = 110,
        Status = 0
    },
    new Flight
    {
        Id = 64,
        FlightNumber = "EK205",
        Airline = "Emirates",
        Aircraft = "Boeing 777",
        Origin = "Dubai",
        Destination = "Abu Dhabi",
        DepartureDateTime = new DateTime(2025, 7, 13, 7, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 13, 7, 45, 0),
        BusinessPrice = 25000.00m,
        EconomyPrice = 8000.00m,
        TotalBusinessSeats = 18,
        AvailableBusinessSeats = 18,
        TotalEconomySeats = 100,
        AvailableEconomySeats = 100,
        Status = 0
    },
    new Flight
    {
        Id = 65,
        FlightNumber = "QF493",
        Airline = "Qantas",
        Aircraft = "Boeing 737",
        Origin = "Sydney",
        Destination = "Melbourne",
        DepartureDateTime = new DateTime(2025, 7, 14, 6, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 14, 8, 0, 0),
        BusinessPrice = 45000.00m,
        EconomyPrice = 17000.00m,
        TotalBusinessSeats = 25,
        AvailableBusinessSeats = 25,
        TotalEconomySeats = 140,
        AvailableEconomySeats = 140,
        Status = 0
    },
    new Flight
    {
        Id = 66,
        FlightNumber = "NZ410",
        Airline = "Air New Zealand",
        Aircraft = "Airbus A320",
        Origin = "Auckland",
        Destination = "Wellington",
        DepartureDateTime = new DateTime(2025, 7, 15, 11, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 15, 12, 10, 0),
        BusinessPrice = 30000.00m,
        EconomyPrice = 10000.00m,
        TotalBusinessSeats = 10,
        AvailableBusinessSeats = 10,
        TotalEconomySeats = 130,
        AvailableEconomySeats = 130,
        Status = 0
    },
    new Flight
    {
        Id = 67,
        FlightNumber = "JL513",
        Airline = "Japan Airlines",
        Aircraft = "Boeing 737",
        Origin = "Tokyo",
        Destination = "Sapporo",
        DepartureDateTime = new DateTime(2025, 7, 16, 15, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 16, 17, 20, 0),
        BusinessPrice = 50000.00m,
        EconomyPrice = 20000.00m,
        TotalBusinessSeats = 20,
        AvailableBusinessSeats = 20,
        TotalEconomySeats = 160,
        AvailableEconomySeats = 160,
        Status = 0
    },
    new Flight
    {
        Id = 68,
        FlightNumber = "LH123",
        Airline = "Lufthansa",
        Aircraft = "Airbus A320",
        Origin = "Frankfurt",
        Destination = "Berlin",
        DepartureDateTime = new DateTime(2025, 7, 17, 14, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 17, 15, 15, 0),
        BusinessPrice = 42000.00m,
        EconomyPrice = 16000.00m,
        TotalBusinessSeats = 16,
        AvailableBusinessSeats = 16,
        TotalEconomySeats = 135,
        AvailableEconomySeats = 135,
        Status = 0
    },
    new Flight
    {
        Id = 69,
        FlightNumber = "CA183",
        Airline = "Air China",
        Aircraft = "Boeing 737",
        Origin = "Beijing",
        Destination = "Shanghai",
        DepartureDateTime = new DateTime(2025, 7, 18, 9, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 18, 11, 20, 0),
        BusinessPrice = 47000.00m,
        EconomyPrice = 18000.00m,
        TotalBusinessSeats = 22,
        AvailableBusinessSeats = 22,
        TotalEconomySeats = 150,
        AvailableEconomySeats = 150,
        Status = 0
    },
    new Flight
    {
        Id = 70,
        FlightNumber = "AC150",
        Airline = "Air Canada",
        Aircraft = "Airbus A321",
        Origin = "Toronto",
        Destination = "Vancouver",
        DepartureDateTime = new DateTime(2025, 7, 19, 8, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 19, 11, 15, 0),
        BusinessPrice = 62000.00m,
        EconomyPrice = 25000.00m,
        TotalBusinessSeats = 24,
        AvailableBusinessSeats = 24,
        TotalEconomySeats = 145,
        AvailableEconomySeats = 145,
        Status = 0
    },

     //same source to location (multiple flights)

     new Flight
     {
         Id = 71,
         FlightNumber = "DL145",
         Airline = "Delta Airlines",
         Aircraft = "Boeing 737",
         Origin = "New York",
         Destination = "Los Angeles",
         DepartureDateTime = new DateTime(2025, 7, 20, 9, 0, 0),
         ArrivalDateTime = new DateTime(2025, 7, 20, 12, 15, 0),
         BusinessPrice = 60000.00m,
         EconomyPrice = 22000.00m,
         TotalBusinessSeats = 20,
         AvailableBusinessSeats = 20,
         TotalEconomySeats = 150,
         AvailableEconomySeats = 150,
         Status = 0
     },

    // Same route, same day — United
    new Flight
    {
        Id = 72,
        FlightNumber = "UA488",
        Airline = "United Airlines",
        Aircraft = "Airbus A321",
        Origin = "New York",
        Destination = "Los Angeles",
        DepartureDateTime = new DateTime(2025, 7, 20, 14, 30, 0),
        ArrivalDateTime = new DateTime(2025, 7, 20, 17, 30, 0),
        BusinessPrice = 61000.00m,
        EconomyPrice = 21500.00m,
        TotalBusinessSeats = 18,
        AvailableBusinessSeats = 18,
        TotalEconomySeats = 160,
        AvailableEconomySeats = 160,
        Status = 0
    },

    // Same route, different day — American Airlines
    new Flight
    {
        Id = 73,
        FlightNumber = "AA301",
        Airline = "American Airlines",
        Aircraft = "Boeing 777",
        Origin = "New York",
        Destination = "Los Angeles",
        DepartureDateTime = new DateTime(2025, 7, 21, 10, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 21, 13, 15, 0),
        BusinessPrice = 63000.00m,
        EconomyPrice = 23000.00m,
        TotalBusinessSeats = 22,
        AvailableBusinessSeats = 22,
        TotalEconomySeats = 140,
        AvailableEconomySeats = 140,
        Status = 0
    },

    // London to Edinburgh — British Airways
    new Flight
    {
        Id = 74,
        FlightNumber = "BA123",
        Airline = "British Airways",
        Aircraft = "Airbus A320",
        Origin = "London",
        Destination = "Edinburgh",
        DepartureDateTime = new DateTime(2025, 7, 20, 8, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 20, 9, 30, 0),
        BusinessPrice = 40000.00m,
        EconomyPrice = 15000.00m,
        TotalBusinessSeats = 15,
        AvailableBusinessSeats = 15,
        TotalEconomySeats = 120,
        AvailableEconomySeats = 120,
        Status = 0
    },

    // Same route, same day — EasyJet
    new Flight
    {
        Id = 75,
        FlightNumber = "EJ777",
        Airline = "EasyJet",
        Aircraft = "Airbus A319",
        Origin = "London",
        Destination = "Edinburgh",
        DepartureDateTime = new DateTime(2025, 7, 20, 13, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 20, 14, 30, 0),
        BusinessPrice = 39000.00m,
        EconomyPrice = 14000.00m,
        TotalBusinessSeats = 10,
        AvailableBusinessSeats = 10,
        TotalEconomySeats = 130,
        AvailableEconomySeats = 130,
        Status = 0
    },

    // Same route, different day — Ryanair
    new Flight
    {
        Id = 76,
        FlightNumber = "RY514",
        Airline = "Ryanair",
        Aircraft = "Boeing 737",
        Origin = "London",
        Destination = "Edinburgh",
        DepartureDateTime = new DateTime(2025, 7, 21, 11, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 21, 12, 30, 0),
        BusinessPrice = 37000.00m,
        EconomyPrice = 13000.00m,
        TotalBusinessSeats = 10,
        AvailableBusinessSeats = 10,
        TotalEconomySeats = 125,
        AvailableEconomySeats = 125,
        Status = 0
    },

    // round trip ( for Id 61 to 70)


    new Flight
    {
        Id = 77,
        FlightNumber = "DL146",
        Airline = "Delta Airlines",
        Aircraft = "Boeing 737",
        Origin = "Los Angeles",
        Destination = "New York",
        DepartureDateTime = new DateTime(2025, 7, 21, 14, 0, 0),
        ArrivalDateTime = new DateTime(2025, 7, 21, 22, 15, 0),
        BusinessPrice = 60000.00m,
        EconomyPrice = 22000.00m,
        TotalBusinessSeats = 20,
        AvailableBusinessSeats = 20,
        TotalEconomySeats = 150,
        AvailableEconomySeats = 150,
        Status = 0
    },
  new Flight
  {
      Id = 78,
      FlightNumber = "BA257",
      Airline = "British Airways",
      Aircraft = "Airbus A320",
      Origin = "Edinburgh",
      Destination = "London",
      DepartureDateTime = new DateTime(2025, 7, 22, 11, 0, 0),
      ArrivalDateTime = new DateTime(2025, 7, 22, 12, 30, 0),
      BusinessPrice = 40000.00m,
      EconomyPrice = 15000.00m,
      TotalBusinessSeats = 15,
      AvailableBusinessSeats = 15,
      TotalEconomySeats = 120,
      AvailableEconomySeats = 120,
      Status = 0
  },
  new Flight
  {
      Id = 79,
      FlightNumber = "AF342",
      Airline = "Air France",
      Aircraft = "Airbus A321",
      Origin = "Nice",
      Destination = "Paris",
      DepartureDateTime = new DateTime(2025, 7, 23, 16, 0, 0),
      ArrivalDateTime = new DateTime(2025, 7, 23, 17, 25, 0),
      BusinessPrice = 38000.00m,
      EconomyPrice = 12000.00m,
      TotalBusinessSeats = 12,
      AvailableBusinessSeats = 12,
      TotalEconomySeats = 110,
      AvailableEconomySeats = 110,
      Status = 0
  },
  new Flight
  {
      Id = 80,
      FlightNumber = "EK206",
      Airline = "Emirates",
      Aircraft = "Boeing 777",
      Origin = "Abu Dhabi",
      Destination = "Dubai",
      DepartureDateTime = new DateTime(2025, 7, 24, 10, 0, 0),
      ArrivalDateTime = new DateTime(2025, 7, 24, 10, 45, 0),
      BusinessPrice = 25000.00m,
      EconomyPrice = 8000.00m,
      TotalBusinessSeats = 18,
      AvailableBusinessSeats = 18,
      TotalEconomySeats = 100,
      AvailableEconomySeats = 100,
      Status = 0
  },
  new Flight
  {
      Id = 81,
      FlightNumber = "QF494",
      Airline = "Qantas",
      Aircraft = "Boeing 737",
      Origin = "Melbourne",
      Destination = "Sydney",
      DepartureDateTime = new DateTime(2025, 7, 25, 9, 0, 0),
      ArrivalDateTime = new DateTime(2025, 7, 25, 10, 30, 0),
      BusinessPrice = 45000.00m,
      EconomyPrice = 17000.00m,
      TotalBusinessSeats = 25,
      AvailableBusinessSeats = 25,
      TotalEconomySeats = 140,
      AvailableEconomySeats = 140,
      Status = 0
  },
  new Flight
  {
      Id = 82,
      FlightNumber = "NZ411",
      Airline = "Air New Zealand",
      Aircraft = "Airbus A320",
      Origin = "Wellington",
      Destination = "Auckland",
      DepartureDateTime = new DateTime(2025, 7, 26, 13, 0, 0),
      ArrivalDateTime = new DateTime(2025, 7, 26, 14, 10, 0),
      BusinessPrice = 30000.00m,
      EconomyPrice = 10000.00m,
      TotalBusinessSeats = 10,
      AvailableBusinessSeats = 10,
      TotalEconomySeats = 130,
      AvailableEconomySeats = 130,
      Status = 0
  },
  new Flight
  {
      Id = 83,
      FlightNumber = "JL514",
      Airline = "Japan Airlines",
      Aircraft = "Boeing 737",
      Origin = "Sapporo",
      Destination = "Tokyo",
      DepartureDateTime = new DateTime(2025, 7, 27, 12, 30, 0),
      ArrivalDateTime = new DateTime(2025, 7, 27, 14, 20, 0),
      BusinessPrice = 50000.00m,
      EconomyPrice = 20000.00m,
      TotalBusinessSeats = 20,
      AvailableBusinessSeats = 20,
      TotalEconomySeats = 160,
      AvailableEconomySeats = 160,
      Status = 0
  },
  new Flight
  {
      Id = 84,
      FlightNumber = "LH124",
      Airline = "Lufthansa",
      Aircraft = "Airbus A320",
      Origin = "Berlin",
      Destination = "Frankfurt",
      DepartureDateTime = new DateTime(2025, 7, 28, 13, 0, 0),
      ArrivalDateTime = new DateTime(2025, 7, 28, 14, 15, 0),
      BusinessPrice = 42000.00m,
      EconomyPrice = 16000.00m,
      TotalBusinessSeats = 16,
      AvailableBusinessSeats = 16,
      TotalEconomySeats = 135,
      AvailableEconomySeats = 135,
      Status = 0
  },
  new Flight
  {
      Id = 85,
      FlightNumber = "CA184",
      Airline = "Air China",
      Aircraft = "Boeing 737",
      Origin = "Shanghai",
      Destination = "Beijing",
      DepartureDateTime = new DateTime(2025, 7, 29, 15, 0, 0),
      ArrivalDateTime = new DateTime(2025, 7, 29, 16, 50, 0),
      BusinessPrice = 47000.00m,
      EconomyPrice = 18000.00m,
      TotalBusinessSeats = 22,
      AvailableBusinessSeats = 22,
      TotalEconomySeats = 150,
      AvailableEconomySeats = 150,
      Status = 0
  },
  new Flight
  {
      Id = 86,
      FlightNumber = "AC151",
      Airline = "Air Canada",
      Aircraft = "Airbus A321",
      Origin = "Vancouver",
      Destination = "Toronto",
      DepartureDateTime = new DateTime(2025, 7, 30, 13, 0, 0),
      ArrivalDateTime = new DateTime(2025, 7, 30, 21, 15, 0),
      BusinessPrice = 62000.00m,
      EconomyPrice = 25000.00m,
      TotalBusinessSeats = 24,
      AvailableBusinessSeats = 24,
      TotalEconomySeats = 145,
      AvailableEconomySeats = 145,
      Status = 0
  },


 // old flights 


 new Flight
 {
     Id = 87,
     FlightNumber = "F870",
     Airline = "American Airlines",
     Aircraft = "Boeing 737",
     Origin = "New York",
     Destination = "Los Angeles",
     DepartureDateTime = new DateTime(2025, 6, 15, 17, 9, 36),
     ArrivalDateTime = new DateTime(2025, 6, 15, 23, 9, 36),
     BusinessPrice = 899.99m,
     EconomyPrice = 299.99m,
     TotalBusinessSeats = 30,
     AvailableBusinessSeats = 30,
     TotalEconomySeats = 150,
     AvailableEconomySeats = 150,
     Status = 0
 },
new Flight
{
    Id = 88,
    FlightNumber = "F871",
    Airline = "Delta Airlines",
    Aircraft = "Airbus A320",
    Origin = "Chicago",
    Destination = "Miami",
    DepartureDateTime = new DateTime(2025, 6, 13, 17, 9, 36),
    ArrivalDateTime = new DateTime(2025, 6, 13, 20, 9, 36),
    BusinessPrice = 699.99m,
    EconomyPrice = 249.99m,
    TotalBusinessSeats = 24,
    AvailableBusinessSeats = 24,
    TotalEconomySeats = 120,
    AvailableEconomySeats = 120,
    Status = 0
},
new Flight
{
    Id = 89,
    FlightNumber = "F872",
    Airline = "United Airlines",
    Aircraft = "Boeing 757",
    Origin = "San Francisco",
    Destination = "Seattle",
    DepartureDateTime = new DateTime(2025, 6, 12, 17, 9, 36),
    ArrivalDateTime = new DateTime(2025, 6, 12, 19, 9, 36),
    BusinessPrice = 599.99m,
    EconomyPrice = 199.99m,
    TotalBusinessSeats = 28,
    AvailableBusinessSeats = 28,
    TotalEconomySeats = 140,
    AvailableEconomySeats = 140,
    Status = 0
},
new Flight
{
    Id = 90,
    FlightNumber = "F873",
    Airline = "British Airways",
    Aircraft = "Airbus A321",
    Origin = "London",
    Destination = "Paris",
    DepartureDateTime = new DateTime(2025, 6, 14, 17, 9, 36),
    ArrivalDateTime = new DateTime(2025, 6, 14, 18, 9, 36),
    BusinessPrice = 499.99m,
    EconomyPrice = 149.99m,
    TotalBusinessSeats = 40,
    AvailableBusinessSeats = 40,
    TotalEconomySeats = 180,
    AvailableEconomySeats = 180,
    Status = 0
},
new Flight
{
    Id = 91,
    FlightNumber = "F874",
    Airline = "Air France",
    Aircraft = "Boeing 737",
    Origin = "Paris",
    Destination = "Berlin",
    DepartureDateTime = new DateTime(2025, 6, 16, 17, 9, 36),
    ArrivalDateTime = new DateTime(2025, 6, 16, 19, 9, 36),
    BusinessPrice = 579.99m,
    EconomyPrice = 179.99m,
    TotalBusinessSeats = 35,
    AvailableBusinessSeats = 35,
    TotalEconomySeats = 160,
    AvailableEconomySeats = 160,
    Status = 0
},
new Flight
{
    Id = 92,
    FlightNumber = "F875",
    Airline = "Qantas",
    Aircraft = "Airbus A320",
    Origin = "Sydney",
    Destination = "Melbourne",
    DepartureDateTime = new DateTime(2025, 6, 11, 17, 9, 36),
    ArrivalDateTime = new DateTime(2025, 6, 11, 18, 9, 36),
    BusinessPrice = 459.99m,
    EconomyPrice = 139.99m,
    TotalBusinessSeats = 42,
    AvailableBusinessSeats = 42,
    TotalEconomySeats = 190,
    AvailableEconomySeats = 190,
    Status = 0
},
new Flight
{
    Id = 93,
    FlightNumber = "F876",
    Airline = "Emirates",
    Aircraft = "Boeing 777",
    Origin = "Dubai",
    Destination = "Singapore",
    DepartureDateTime = new DateTime(2025, 6, 18, 17, 9, 36),
    ArrivalDateTime = new DateTime(2025, 6, 19, 0, 9, 36),
    BusinessPrice = 999.99m,
    EconomyPrice = 399.99m,
    TotalBusinessSeats = 50,
    AvailableBusinessSeats = 50,
    TotalEconomySeats = 200,
    AvailableEconomySeats = 200,
    Status = 0
}
);



        }
    }
}